/// <reference path="../../packages/com.adobe.incopy/references.d.ts"/>

declare namespace Adobe {
	namespace Incopy {
		class TrapEndTypes extends Adobe.Csawlib.CSEnumBase {
			/**
			 * @type {Adobe.Csawlib.CSEnumSharedCache}
			 * @readonly
			 */
			public static readonly enumCache: Adobe.Csawlib.CSEnumSharedCache;
			/**
			 * Shapes the end of the trap to keep it away from the 
			 * intersecting object.
			 * @type {Adobe.Incopy.TrapEndTypes}
			 * @readonly
			 */
			public static readonly MITER_TRAP_ENDS: Adobe.Incopy.TrapEndTypes;
			/**
			 * Alias for MITER_TRAP_ENDS. Shapes the end of the trap to 
			 * keep it away from the intersecting object.
			 * @type {Adobe.Incopy.TrapEndTypes}
			 * @readonly
			 */
			public static readonly miterTrapEnds: Adobe.Incopy.TrapEndTypes;
			/**
			 * Reshapes the trap generated by the lightest neutral density 
			 * object so that it wraps around the point where the three 
			 * objects intersect.
			 * @type {Adobe.Incopy.TrapEndTypes}
			 * @readonly
			 */
			public static readonly OVERLAP_TRAP_ENDS: Adobe.Incopy.TrapEndTypes;
			/**
			 * Alias for OVERLAP_TRAP_ENDS. Reshapes the trap generated by 
			 * the lightest neutral density object so that it wraps around 
			 * the point where the three objects intersect.
			 * @type {Adobe.Incopy.TrapEndTypes}
			 * @readonly
			 */
			public static readonly overlapTrapEnds: Adobe.Incopy.TrapEndTypes;
			/**
			 * Constructor
			 * @returns {void}
			 */
			public constructor();
		}
	}
}