/// <reference path="../../packages/com.adobe.bridge/index.d.ts"/>

declare namespace Adobe {
	namespace Bridge {
		/**
		 * Encapsulates information about how a search result node was 
		 * generated by a node-handler’s getBridgeUriForSearch() 
		 * method. Returned by the ExtensionModel.getSearchDetails() 
		 * method for a search-result node.
		 */
		class SearchDetails extends Adobe.Csawlib.CSHostObject {
			/**
			 * A SearchSpecification object that was used to generate this 
			 * search result.
			 */
			public searchSpecification: Adobe.Bridge.SearchSpecification;
			/**
			 * The Bridge URI for the search target node that was used to 
			 * generate this search result.
			 */
			public searchTargetUri: string;
			public constructor();
			/**
			 * @param {any[]} args
			 */
			protected createWithArgs(args: any[]): void;
		}
	}
}